begin
create table course (code varchar(10),name varchar(60),semester int(1),credits int(2),branch varchar(3), primary key(code));
insert into course(code,name,semester,credits,branch) values 
('IS31','Engineering Mathematics - III',3,4,'ISE'),
('IS32','Computer Organization and Architecture',3,4,'ISE'),
('IS33','Discrete Mathematical Structures',3,4,'ISE'),
('IS34','Data Communications',3,3,'ISE'),
('IS35','Data Structures',3,4,'ISE'),
('IS36','Object Oriented Programming with Java',3,4,'ISE'),
('ISL37','Data Structures Lab',3,1,'ISE'),
('ISL38','Object Oriented Programming with Java Lab',3,1,'ISE'),
('IS41','Engineering Mathematics - IV',4,4,'ISE'),
('IS42','Operating Systems',4,3,'ISE'),
('IS43','Operations Research',4,4,'ISE'),
('IS44','Finite Automata and Formal Languages',4,4,'ISE'),
('IS45','Design and Analysis of Algorithms ',4,4,'ISE'),
('IS46','Microcontrollers',4,4,'ISE'),
('ISL47','Design and Analysis of Algorithms Lab',4,1,'ISE'),
('ISL48','Microcontrollers Lab ',4,1,'ISE'),
('IS51','Computer Networks',5,4,'ISE'),
('IS52','Operations Research',5,4,'ISE'),
('IS53','Operating Systems',5,3,'ISE'),
('IS54','Database Management Systems',5,4,'ISE'),
('IS55','Intellectual Property Rights',5,2,'ISE'),
('ISL56','Computer Networks Laboratory',5,1,'ISE'),
('ISL57','Database Management Systems Laboratory',5,1,'ISE'),
('ISL58','Scripting Languages Laboratory',5,2,'ISE'),
('ISEA1','Digital Image Processing',5,4,'ISE'),
('IS61','System Software',6,4,'ISE'),
('IS62B','Object Oriented Analysis and Design Patterns using JAVA',6,4,'ISE'),
('IS63','Java and J2EE',6,4,'ISE'),
('ISL64','Mini-Project',6,6,'ISE'),
('ISL65','System Software Laboratory',6,1,'ISE'),
('ISL66','Object Oriented Analysis and Design Patterns Laboratory',6,1,'ISE'),
('ISL67','Java and J2EE Laboratory',6,1,'ISE'),
('ISEB1','Machine Learning',6,4,'ISE'),
('IS71','Data Mining',7,4,'ISE'),
('IS72','Distributed Computing',7,4,'ISE'),
('IS73','Information Security',7,4,'ISE'),
('ISL74','Data Mining Lab',7,1,'ISE'),
('ISL75','Distributed Computing Lab',7,1,'ISE'),
('ISEC1','Software Testing',7,4,'ISE'),
('ISED1','System Simulation and Modeling',7,4,'ISE'),
('ISEE1','Data Science',7,4,'ISE'),
('ISELE','Open Elective',8,4,'ISE'),
('ISIN','Internship',8,4,'ISE'),
('ISP','Senior Project',8,16,'ISE'),
('ISEAC','Extra/Co-Curricular Activities',8,2,'ISE'),
('CS31','Engineering Mathematics-III',3,4,'CSE'),
('CS32','Data Structures',3,4,'CSE'),
('CS33','Discrete Mathematical Structures',3,4,'CSE'),
('CS34','Theory of Computation',3,4,'CSE'),
('CS35','Analog and Digital Design',3,4,'CSE'),
('CS36','Object Oriented Programming',3,3,'CSE'),
('CSL37','Object Oriented Programming Laboratory',3,1,'CSE'),
('CSL38','Data Structures Laboratory',3,1,'CSE'),
('CS41','Engineering Mathematics-IV',4,4,'CSE'),
('CS42','Design and Analysis of Algorithms',4,4,'CSE'),
('CS43','Microprocessors and Microcontrollers',4,4,'CSE'),
('CS44','Data Communication',4,4,'CSE'),
('CS45','Computer Organization and Architecture',4,4,'CSE'),
('CS46','Software Engineering',4,3,'CSE'),
('CSL47','Algorithms Laboratory',4,1,'CSE'),
('CSL48','Python Programming Laboratory',4,1,'CSE'),
('CS51','Operating Systems',5,4,'CSE'),
('CS52','Database Systems',5,4,'CSE'),
('CS53','Computer Networks',5,4,'CSE'),
('CS54','Java Programming',5,4,'CSE'),
('CS55','Intellectual Property Rights',5,2,'CSE'),
('CSE01','Data Mining',5,4,'CSE'),
('CSL57','Java Programming Laboratory',5,1,'CSE'),
('CSL58','Database Systems Laboratory',5,1,'CSE'),
('CSL59','Computer Networks Laboratory',5,1,'CSE'),
('CS61','Compiler Design',6,4,'CSE'),
('CS62','Software Engineering',6,4,'CSE'),
('CS63','Unix System Programming and Web Technologies',6,4,'CSE'),
('CS64','Mini Project',6,6,'CSE'),
('CSE07','Mobile Computing',6,4,'CSE'),
('CSL66','Unix System Programming & Compiler Design Laboratory',6,1,'CSE'),
('CSL67','IoT / Embedded Systems Laboratory',6,1,'CSE'),
('CSL68','Web Technologies Laboratory',6,1,'CSE'),
('CS71','Computer Network Security',7,4,'CSE'),
('CS72','High Performance Computing',7,4,'CSE'),
('CS73','Data Analytics',7,4,'CSE'),
('CSE14','Cloud Computing',7,4,'CSE'),
('CSE19','Analysis of Computer Data Networks',7,4,'CSE'),
('CSE24','Project management & Engg Economics',7,4,'CSE'),
('CSL74','High Performance Computing Laboratory',7,1,'CSE'),
('CSL75','Data Analytics Laboratory',7,1,'CSE'),
('CSELE','Institutional Elective',8,4,'CSE'),
('CSIN','Internship/Departmental Elective',8,4,'CSE'),
('CSP','Project Work',8,16,'CSE'),
('CSEAC','Extra-Curricular/CoCurricular Activities',8,2,'CSE');
end;
/
